name: check

on: [pull_request]

jobs:
  pre:
    name: Prerequisites
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enforce CLA signature
        run: curl https://raw.githubusercontent.com/shapesecurity/CLA/HEAD/cla-travis.sh | bash

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    name: Test on node ${{ matrix.node_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      # this package has no tests
